### PR TITLE
[MRG] MAINT: merge two overlapping tests into one in test_numpy_pickle.py

### PR DESCRIPTION
**Pull request by lesteve**
@aabadie I got there from one of your comment in another PR.

### CODE REVIEW

**Comment by aabadie** [comment]
The idea behind this PR is appealing but it skips the compatibility checks between python versions. AFAIR, I added the separate compression check to work around this problem.

**Comment by lesteve** [comment]
> The idea behind this PR is appealing but it skips the compatibility checks between python versions. AFAIR, I added the separate compression check to work around this problem.

I don't why this could be the case but it looks like coveralls is agreeing so I'll have to look into in more details.

**Comment by lesteve** [comment]
> I don't why this could be the case but it looks like coveralls agrees so I'll have to look into in more details.

Turns out your test was missing `*` in the glob, so it wasn't testing anything ... In other words `compress_filenames` was `[]`.

**Comment by lesteve** [comment]
Another one of these rare cases, where coveralls is actually very useful.

**Comment by aabadie** [comment]
@lesteve. I'm fine with this change. Let's merge it.

**Comment by lesteve** [comment]
Thanks!

**Pull request merged**
