### PR TITLE
Remove `check_pickle` argument in `delayed`.

### PR DESCRIPTION
**Pull request by jjerphan**
**Context**: `check_pickle` should have been removed in 0.13.0 as indicated in the `DeprecationWarning`.

**Changes**: This PR removes this argument, behavior, and the associated test.

**Associated Issue:**  #900

### CODE REVIEW

**Comment by pierreglaser** [comment]
Hi @jjerphan, why was this closed?

**Comment by jjerphan** [comment]
Hi @pierreglaser ; I just made some housekeeping on my stalled PRs, I reopen it now.

**Comment by pierreglaser** [comment]
@jjerphan If you find some time, feel free to finish this up :) we should release `joblib` early next week.

**Comment by jjerphan** [comment]
Hi @pierreglaser. I haven't managed to find a reason for the "failure" of the codecov pipeline.

**Comment by pierreglaser** [comment]
Don't worry about the `codecov` complaints. This issue is affecting a lot of PRs, and I think `joblib` should use a coverage threshold like [scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/a655de515e24515fff0007100dc9d49b5126b223/.codecov.yml#L3-L21) does.

**Comment by pierreglaser** [comment]
@ogrisel if you want to take a look :)

**Comment by jjerphan** [comment]
OK, thank you @pierreglaser for this piece of feedback.

**Comment by jjerphan** [comment]
Small up.

**Review by tomMoral — APPROVED** [review]
This seems a bit overdue! thx @jjerphan.

Could you simply add an entry in the change log saying that you removed this deprecated argument?

**Comment by jjerphan** [comment]
@tomMoral: thanks for the follow up! :slightly_smiling_face: 

CI checks on Azure are still failing but it is unrelated to those changes.

**Comment by ogrisel** [comment]
> CI checks on Azure are still failing but it is unrelated to those changes.

It looks all green to me.

**Comment by ogrisel** [comment]
Thanks!

**Comment by tomMoral** [comment]
Thanks!

**Comment by dmalzl** [comment]
Hi there,

I am currently trying to run [pomgranate](https://github.com/jmschrei/pomegranate) to fit a hidden markov model to some data. This library uses joblib to parallelize the model training. However, when I try to train it I get the following error:
```python
Empty                                     Traceback (most recent call last)
~/.conda/envs/mypython/lib/python3.6/site-packages/joblib/parallel.py in dispatch_one_batch(self, iterator)
    819             try:
--> 820                 tasks = self._ready_batches.get(block=False)
    821             except queue.Empty:

~/.conda/envs/mypython/lib/python3.6/queue.py in get(self, block, timeout)
    160                 if not self._qsize():
--> 161                     raise Empty
    162             elif timeout is None:

Empty:

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-7-dcc6125ae320> in <module>
----> 1 df = hmm(df, 3)

~/.conda/envs/mypython/lib/python3.6/site-packages/hmm_bigwigs/bigwig_hmm.py in hmm(df, num_states)
     40     vals = df["value"].values
     41     model = HiddenMarkovModel.from_samples(
---> 42         NormalDistribution, X=[vals], n_components=num_states
     43     )
     44     states = model.predict(vals)

~/.conda/envs/mypython/lib/python3.6/site-packages/pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.from_samples()

~/.conda/envs/mypython/lib/python3.6/site-packages/pomegranate/kmeans.pyx in pomegranate.kmeans.Kmeans.fit()

~/.conda/envs/mypython/lib/python3.6/site-packages/pomegranate/kmeans.pyx in genexpr()

~/.conda/envs/mypython/lib/python3.6/site-packages/joblib/parallel.py in __call__(self, iterable)
   1039             # remaining jobs.
   1040             self._iterating = False
-> 1041             if self.dispatch_one_batch(iterator):
   1042                 self._iterating = self._original_iterator is not None
   1043

~/.conda/envs/mypython/lib/python3.6/site-packages/joblib/parallel.py in dispatch_one_batch(self, iterator)
    829                 big_batch_size = batch_size * n_jobs
    830
--> 831                 islice = list(itertools.islice(iterator, big_batch_size))
    832                 if len(islice) == 0:
    833                     return False

~/.conda/envs/mypython/lib/python3.6/site-packages/pomegranate/kmeans.pyx in genexpr()

TypeError: delayed() got an unexpected keyword argument 'check_pickle'
```

I checked the input file and every variable I feed the model and all is fine there. I tried to find out where the `'check_pickle'` kwarg came from but I was not able to find the culprit. Do you know what's going on?

Thanks

**Comment by jjerphan** [comment]
@dmalzl: the `check_pickle` has been removed from `delayed` in joblib. This has been fixed accordingly in pomegranate by https://github.com/jmschrei/pomegranate/commit/42d14bebc44ffd4a778b2a6430aa845591b7c3b7. Updating pomgranate to  v0.14.0 should fix the problem:
```bash
pip install - U pomegranate
```

**Comment by dmalzl** [comment]
Ah okay. Since I just installed it today, I thought I already had the newest version. Seems the conda recipe is outdated then. That's what you get from blind trust.

Anyway, works now after updating.
Thanks for the help

**Comment by jjerphan** [comment]
You're welcome.

**Pull request merged**
