### PR TITLE
Fix dask scatter deadlock

### LINKED ISSUE #852: KeyError with joblib and sklearn cross_validate
This was originally reported as https://github.com/dask/distributed/issues/2532

I tried be reproduce it on joblib master with scikit-learn 0.20.2 as follows.

```python
import os
os.environ['SKLEARN_SITE_JOBLIB'] = "1"
from dask.distributed import Client
from sklearn import datasets, linear_model
from sklearn.model_selection import cross_validate
import joblib


client = Client(processes=False)
joblib.parallel_backend('dask')

diabetes = datasets.load_diabetes()
X = diabetes.data[:150]
y = diabetes.target[:150]
model = linear_model.LinearRegression()

cv_results = cross_validate(model, X, y, cv=10, return_train_score=False,
                            verbose=100)
```

However this seem to freeze without reporting the original error. Instead when I interrupt with ctrl-c I get:

```
[Parallel(n_jobs=-1)]: Using backend DaskDistributedBackend with 4 concurrent workers.
[CV]  ................................................................
[CV] .................................... , score=0.587, total=   0.0s
[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    0.0s
^CTraceback (most recent call last):
  File "/home/ogrisel/code/joblib/joblib/_dask.py", line 223, in maybe_to_futures
    f = call_data_futures[arg]
  File "/home/ogrisel/code/joblib/joblib/_dask.py", line 56, in __getitem__
    ref, val = self._data[id(obj)]
KeyError: 140545475489024

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ogrisel/tmp/joblib_dask_freeze.py", line 18, in <module>
    verbose=100)
  File "/home/ogrisel/code/scikit-learn/sklearn/model_selection/_validation.py", line 231, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ogrisel/code/joblib/joblib/parallel.py", line 924, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/ogrisel/code/joblib/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/ogrisel/code/joblib/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/ogrisel/code/joblib/joblib/_dask.py", line 254, in apply_async
    func, args = self._to_func_args(func)
  File "/home/ogrisel/code/joblib/joblib/_dask.py", line 243, in _to_func_args
    args = list(maybe_to_futures(args))
  File "/home/ogrisel/code/joblib/joblib/_dask.py", line 231, in maybe_to_futures
    [f] = self.client.scatter([arg])
  File "/home/ogrisel/code/distributed/distributed/client.py", line 1875, in scatter
    asynchronous=asynchronous, hash=hash)
  File "/home/ogrisel/code/distributed/distributed/client.py", line 676, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/home/ogrisel/code/distributed/distributed/utils.py", line 275, in sync
    e.wait(10)
  File "/opt/python3.7/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/python3.7/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
```

### PR DESCRIPTION
**Pull request by pierreglaser**
Builds on top of #910 
Fixes #852 

(I'm still not 100% sure of whats going on here). This PR ensures the synchronous execution of distributed `scatter` operations by not running joblib's callbacks directly into `distributed` client event loop. In this situation, the operations can safely be made blocking.

I tried running the sklearn example in #852 and it runs fine. Hopefully the results are correct also.
@ogrisel

### CODE REVIEW

**Comment by pierreglaser** [comment]
Also, @mrocklin feel free to chime and share your thoughts :)

**Comment by julioasotodv** [comment]
@pierreglaser I just tried this patch with the following code:

```python
import numpy as np

from dask.distributed import Client, LocalCluster
from joblib import Parallel, delayed, parallel_backend

def sum_values(array, scalar):
    return (array + scalar).sum()

cluster = LocalCluster()
client = Client(cluster)

with parallel_backend("dask"):
    results = Parallel()(delayed(sum_values)(np.zeros(i), 5) for i in range(50000, 50010))

print(results)
```

And it still gets hung forever (until I Ctrl+C) :(

**Comment by pierreglaser** [comment]
Thanks for the feedback -- I'm looking at it.

**Comment by julioasotodv** [comment]
@pierreglaser sorry, edited my previous comment. It DOES work now :) (was testing wrong branch)

**Comment by pierreglaser** [comment]
Great!

**Comment by jjerphan** [comment]
It also work for me with the snippet provided by @julioasotodv. 🎉🎉

**Comment by jjerphan** [comment]
I've also tried the [snippet provided by @ogrisel](https://github.com/joblib/joblib/issues/852#issue-415517189) on #852 (that comes from [`distributed#2532`](https://github.com/dask/distributed/issues/2532) and it also works now.

<details>
<summary> Python packages used</summary>
<pre>
backcall==0.1.0
bokeh==0.13.0
Click==7.0
cloudpickle==1.2.1
dask==1.2.2
decorator==4.4.0
-e git+https://github.com/jjerphan/distributed.git@6ea010bcf21db7445bd26286966f59a7e75ab390#egg=distributed
HeapDict==1.0.0
ipython==7.7.0
ipython-genutils==0.2.0
jedi==0.14.1
Jinja2==2.10.1
-e git+https://github.com/pierreglaser/joblib.git@f0e687901adf309dc7e7f47af5a8d901383e67eb#egg=joblib
MarkupSafe==1.1.1
msgpack==0.6.1
numpy==1.15.4
packaging==19.0
pandas==0.23.4
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
prompt-toolkit==2.0.9
psutil==5.6.3
ptyprocess==0.6.0
Pygments==2.4.2
pyparsing==2.4.1.1
python-dateutil==2.8.0
pytz==2019.1
PyYAML==5.1.1
scikit-learn==0.20.3
scipy==1.1.0
six==1.12.0
sortedcontainers==2.1.0
tblib==1.4.0
toolz==0.10.0
tornado==5.1.1
traitlets==4.3.2
wcwidth==0.1.7
zict==1.0.0
</pre>
</details>

**Comment by jlopezpena** [comment]
I have tested this PR and verified it also fixes the problem I reported in https://github.com/dask/dask/issues/2665

**Comment by jakirkham** [comment]
@pierreglaser , is this PR still waiting on something or is it ready to merge?

**Comment by pierreglaser** [comment]
It's missing a review by a core dev. @ogrisel should be back from vacations in a week or so.

**Comment by ogrisel** [comment]
Ok I was trying to see if you could do a full async / no-blocking version but it's sounds too cumbersome and would probably require a significant refactoring of joblib backends. I will push a what's new entry to re-trigger CI and then merge this PR.

**Comment by jakirkham** [comment]
Thanks @ogrisel and @pierreglaser! 😀

**Comment by mrocklin** [comment]
Thanks all

**Pull request merged**
