### PR TITLE
[MRG+1] Fix format_stack with compiled code (e.g. .so or .pyd) in the traceback

### LINKED ISSUE #101: joblib doesn't propogate correct exception, raises SyntaxError instead
Whereas multiprocessing propagates the RuntimeError: Error during user-specified initialization

joblib generates a very strange SyntaxError -- I have no idea how I could specify an encoding in a compiled extension!

    ======================================================================
    ERROR: test_user_init_unspecified (pystan.tests.test_problems.TestStanfit)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/abr/documents/pystan/pystan-ariddell/pystan/tests/test_problems.py", line 30, in test_user_init_unspecified
        pystan.stan(model_code=model_code, iter=10, chains=1, seed=2, data=data, init=[dict(mu=4)], warmup=0)
      File "/home/abr/documents/pystan/pystan-ariddell/pystan/api.py", line 321, in stan
        n_jobs=n_jobs, **kwargs)
      File "/home/abr/documents/pystan/pystan-ariddell/pystan/model.py", line 650, in sampling
        ret_and_samples = Parallel(n_jobs)(delayed(call_sampler_star)(args) for args in call_sampler_args)
      File "/home/abr/documents/pystan/pystan-ariddell/pystan/external/joblib/parallel.py", line 602, in __call__
        self.retrieve()
      File "/home/abr/documents/pystan/pystan-ariddell/pystan/external/joblib/parallel.py", line 480, in retrieve
        self._output.append(job.get())
      File "/usr/lib/python3.3/multiprocessing/pool.py", line 564, in get
        raise self._value
    nose.proxy.SyntaxError: invalid or missing encoding declaration for '/tmp/tmp5pc7xw/pystan/stanfit4anon_model_652395f2575ceb009e57546b592d498e.cpython-33m.so'

### PR DESCRIPTION
**Pull request by lesteve**
Fixes #101.

Took the fix from IPython.core.ultratb.py

### CODE REVIEW

**Comment by aabadie** [comment]
@lesteve, in case you missed it, tests are broken on Travis under Python 3.3.

**Comment by aabadie** [comment]
All green +1

**Comment by lesteve** [comment]
I forgot to add a comment about the addition of SyntaxError in the code, I'll do that soonish.

**Comment by aabadie** [comment]
> I forgot to add a comment about the addition of SyntaxError in the code, I'll do that soonish.

Ok, let me know when it's done.

**Comment by lesteve** [comment]
@aabadie I added the aforementioned comment and an entry in whats_new.rst.

**Comment by aabadie** [comment]
LGTM, merging. Thanks !

**Comment by amueller** [comment]
Awesome, thanks!
I'd love to have this in sklearn 0.8.
@ogrisel thoughts?

**Pull request merged**
