### PR TITLE
ENH update loky 2.4.0

### PR DESCRIPTION
**Pull request by tomMoral**
Bump the version of `loky` to 2.4.0.

This update changes the default behavior of `joblib`: `cloudpickle` is used by default to serialize the tasks. Note that this might cause some performance drop in particular for large python objects.

### CODE REVIEW

**Comment by ogrisel** [comment]
@tomMoral The failing test is expected on windows: it's no longer possible to naively use any interactively defined functions with the multiprocessing backend with the spawn start method.

I think we should just skip this test under windows with the multiprocessing backend.

**Comment by ogrisel** [comment]
Let me resolve the conflict with master.

**Comment by ogrisel** [comment]
Appveyor is confused by the merge commit done by the github web UI.

**Comment by ogrisel** [comment]
I rand the scikit-learn tests from scikit-learn master with this branch of joblib and all tests pass.

**Comment by ogrisel** [comment]
I confirm that this branch of joblib fixes the pickling issue reported in https://github.com/scikit-learn/scikit-learn/issues/12250.

**Comment by tomMoral** [comment]
Note that before merging this PR, we need to do a bug-fix release of `loky2.4.1` as it is now in `2.4.1dev0`. I can do it once all the test are green and we are happy with the PR state.

Another missing part in this PR is to document the `set_loky_pickler` and the wrapper in the `joblib` documentation.

**Comment by ogrisel** [comment]
Ooops I deleted this comment by mistake:

This fixes: https://github.com/scikit-learn/scikit-learn/issues/12250.

**Comment by ogrisel** [comment]
@tomMoral alright let's release loky 2.4.1 from the current master and re-update this joblib PR with it.

**Comment by ogrisel** [comment]
We got an error on appveyor with:

```
IOError: [Errno 13] Permission denied: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\pytest-of-appveyor\\pytest-0\\test_concurrency_safe_write_mu0\\test.pkl'
```

in `test_concurrency_safe_write` from `joblib\test\test_store_backends.py`.

This is annoying but I don't think it's related to loky.

**Pull request merged**
