### PR TITLE
Fix joblib.test.test_hashing.test_dtype random failure

### LINKED ISSUE #250: Random failure of joblib.test.test_hashing.test_dtype with python 3
This will fail with python 3 after a while:

```
for i in $(seq 0 100); do nosetests joblib/test/test_hashing.py -m test_dtype --pdb; done
```

This is related with dictionary order randomization of python 3 since setting PYTHONHASHSEED gets rid of the problem.

A small stand-alone snippet reproducing the problem (pretty much joblib.test.test_hashing.test_dtype):

```python
import numpy as np
import pickle

from joblib import hashing


def main():
    a = np.dtype([('f1', np.uint), ('f2', np.int32)])
    b = a
    c = pickle.loads(pickle.dumps(a))
    if hashing.hash([a, c]) != hashing.hash([a, b]):
        print('FAILED')

if __name__ == '__main__':
    main()
```

### PR DESCRIPTION
**Pull request by lesteve**
with python 3. Fix #250.

Rather than trying to pickle numpy.dtype objects, which
give rise to multiple problems with hashing, we used its .desr
attribute which is a full description of the dtype.

This allow not to rely on the persistent_id workaround. The reason it
wasn't working in the first place is that because joblib.dumps(dt) is
not stable across python runs, because the order of dt.fields
changes (dict order randomization in python3).

@arthurmensch if you want to have a look.

### CODE REVIEW

**Comment by ogrisel** [comment]
While I agree this fix is fine, I think we should also make the hash of fields deterministic (independent of attribute ordering).

**Comment by ogrisel** [comment]
LGTM, merging.

**Comment by ogrisel** [comment]
BTW @GaelVaroquaux you might be interested in this.

**Comment by arthurmensch** [comment]
Nice comment, ugly bug !

**Comment by pierreglaser** [comment]
> because the order of dt.fields changes (dict order randomization in python3)

`joblib` auto-sorts `dict` objects when hashing right? Am I missing something?

**Pull request merged**
