### PR TITLE
[MRG] Parallel backend parameters

### PR DESCRIPTION
**Pull request by ogrisel**
This addresses @mrocklin's feature request in #322. It builds on top of #321.

### CODE REVIEW

**Comment by mrocklin** [comment]
This looks good to me

**Comment by ogrisel** [comment]
Fixed the style issue and amended my last commit. BTW this PR also makes it possible to pass a backend instance directly if you don't want to register it.

**Comment by ogrisel** [comment]
Weird there was a seemingly unrelated travis failure in the python 3.4 without nunpy:

```
======================================================================
FAIL: joblib.test.test_memory.test_memory_warning_collision_detection(3, 2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/testenv/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
nose.proxy.AssertionError: 3 != 2
    '3 != 2' = '%s != %s' % _common_shorten_repr(3, 2)
    '3 != 2' = self._formatMessage('3 != 2', '3 != 2')
>>  raise self.failureException('3 != 2')
```

@lesteve have you already seen this before? I will re-run that job to check whether it's deterministic or not.

**Comment by ogrisel** [comment]
I created #326 to track the random failure I observed in this PR but that is not related to the change I made here.

**Pull request merged**
