### PR TITLE
[MRG+1] activate coverage also with python 2.7

### PR DESCRIPTION
**Pull request by aabadie**
Testing if codecov merges the coverages generated with the 2 builds (python 2.7 and python ~~3.5~~ 3.6).

### CODE REVIEW

**Comment by aabadie** [comment]
It indeed merges the results and thus looks much better :)

**Comment by GaelVaroquaux** [comment]
Yes, it's pretty neat! Good job!

+1 for merge.

**Comment by aabadie** [comment]
Also run coverage with the build that doesn't have numpy will increase again coverage (lots of ImportError catches covered), I just pushed a commit with this change.

**Comment by aabadie** [comment]
I feel really enthusiastic with codecov : looking at the coverage reports, I can find things that could be improved (useless code, untested but testable parts, etc). It's a great tool to produce better code !

**Comment by lesteve** [comment]
You probably want to have a codecov.yml to disable comments, like they do in [loky](https://github.com/tomMoral/loky/blob/master/codecov.yml).

**Comment by aabadie** [comment]
> You probably want to have a codecov.yml to disable comments

Thanks for the tip, I added that.

**Comment by lesteve** [comment]
> Thanks for the tip, I added that.

Actually I read the docs in more details and it looks like codecov only posts one comment and then edits it on each further commit: https://docs.codecov.io/docs/pull-request-comments#section-behavior.

This means that it causes only one email rather than spamming on each commit. My take on it is that the report is quite useful, so I would be in favour of removing codecov.yml. Sorry for changing my mind.

**Comment by lesteve** [comment]
Enabling the coverage on Windows jumps to mind as well. Can be done in a separate PR.

**Comment by lesteve** [comment]
Can you add the COVERAGE for the JOBLIB_MULTIPROCESSING=0 as well?

**Comment by aabadie** [comment]
I pushed a commit for appveyor but paths are changed during the run and codecov can't find the coverage file. I'll try that in a separate PR.
It should be good to go now.

**Comment by lesteve** [comment]
Great stuff, thanks, merging!

**Pull request merged**
