### PR TITLE
Support of Ray backend

### PR DESCRIPTION
**Pull request by AmeerHajAli**
Adding support of Ray backend:
https://ray.readthedocs.io

runs using the following API:

with joblib.parallel_backend('ray'):   
    ...

### CODE REVIEW

**Comment by ogrisel** [comment]
Thanks @AmeerHajAli for the contribution! I am not sure if others would prefer to have an dedicated package (e.g. joblib-ray) or not but in any case we would need some tests :)

**Comment by GaelVaroquaux** [comment]
> prefer to have an dedicated package (e.g. joblib-ray)

Yes, like we did for spark.

> or not but in any case we would need some tests :)

Indeed, the separate package should have a good CI.

**Comment by AmeerHajAli** [comment]
I am happy to add the tests. Just to be sure I am following, the code will not be hosted on this repo and instead, it will be on the ray repo for instance?

**Comment by tomMoral** [comment]
I would say either on ray's repo or as a repo in the joblib organization
such as we did for joblib-spark: https://github.com/joblib/joblib-spark

**Pull request closed without merging**
