### PR TITLE
n_jobs parameter in instantiation of Parallel should be an integer

### PR DESCRIPTION
**Pull request by androids-electric-sheep**
Based on https://github.com/joblib/joblib/issues/1539

### CODE REVIEW

**Comment by fcharras** [comment]
Thanks for the PR @androids-electric-sheep, can you give a bit more context about what is the current behavior, does it fail if it's not an int ? (what about n_jobs=3.0, n_jobs="3"). So we know if the PR is about generating a better, earlier error message, or actually add constraints on the input type that didn't exist before.

**Comment by androids-electric-sheep** [comment]
From the issue this PR is based on, and reproduced locally using the example code provided, if a float is provided to the n_jobs parameter slicing will later fail because it requires an int. 

So it's a combination of both really, adding the type constraint and then providing a more understandable error message if it's violated

**Comment by tomMoral** [comment]
Hello! Thanks for the PR!
We decided to go with a more permissive behavior (try to convert to int else fail).

We are trying to make a release by Friday so I changed the PR directly and made the test cover more cases.
Thanks for the contrib!

**Comment by tomMoral** [comment]
The failure in the CI is unrelated, merging this PR.

**Pull request merged**
