### PR TITLE
[MRG] enable codecov on appveyor

### PR DESCRIPTION
**Pull request by aabadie**
Testing codecov with appveyor.

### CODE REVIEW

**Comment by aabadie** [comment]
Now it passes but I had to run pytest from the source directory instead of C:\\ as stated in the removed comment.
I don't know if it's fine or not.

**Comment by ogrisel** [comment]
Fine with me. @lesteve what do you think?

**Comment by lesteve** [comment]
> Fine with me. @lesteve what do you think?

I would still try to run pytest on the package rather than the folder to avoid problems like missing data files in setup.py. I worked on this yesterday and I have #497 that may be close to actually working.

**Comment by ogrisel** [comment]
Alright let's close this PR in favor of #497 as soon as you get it to work then.

**Pull request closed without merging**
