### PR TITLE
[MRG] make BinaryZlibFile seekable

### PR DESCRIPTION
**Pull request by aabadie**
Related to #398.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Nice! Simple and elegant.

Does it have any impact on speed?

**Comment by aabadie** [comment]
> Nice! Simple and elegant.

Sure it's simple, but do we really need this in joblib ? BinaryZlibFile is only here for internal use and should be used outside of joblib. Seeking in a compressed stream is bad in term of performance as one has to decompress when seeking in the stream.
To me this PR shows that we can do it but I wonder it's worth it in joblib.

> Does it have any impact on speed?

I didn't try to compare performance between both solutions. But [this link](http://rabexc.org/posts/io-performance-in-python) can gives some information.

**Comment by aabadie** [comment]
A few benchmarks computed with the `bench_pickle.py` script. I ran the following command with python 3.5/2.7 on branches master/pr399:
```
python benchmarks/bench_pickle.py -m --tries 1 --compressor zlib --compress 3 -a --shape 5000 5000
```


| Python |  branch |         Dataset |      strategy |   write speed (s) |     read speed (s) |  max memory during write (MB) |   max memory during read (MB) |  disk usage (MB) |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 3.5 |  master |       Big array |        zlib 3 |   7.324 |   1.4647 |       35.3 |      190.7 |   180.9 |
| 3.5 |  pr |  Big array |        zlib 3 |   7.313 |   1.3495 |       36.0 |      190.7 |   180.9 |
| 2.7 |  master |  Big array |        zlib 3 |   7.553 |   1.3594 |       34.3 |      190.7 |   180.9 |
| 2.7 |  pr |  Big array |        zlib 3 |   7.353 |   1.3592 |       35.8 |      190.7 |   180.9 |

As one can see, there's no performance change.

**Comment by GaelVaroquaux** [comment]
> As one can see, there's no performance change.

OK, then +1 for merge!

Thanks

**Comment by lesteve** [comment]
Merged, thanks!

**Pull request merged**
