### PR TITLE
[WIP] ENH add in_background_thread option in parallel_backend

### PR DESCRIPTION
**Pull request by tomMoral**
Add an option to allow running `Parallel` call in background threads.

The idea is that the call to `Parallel` should be wrapped in a context manager with `parallel_backend` and option `in_background_thread=True`:

```python
import os
import threading
from time import sleep
from joblib import parallel_backend, delayed, Parallel


def sleep_and_return_pid():
    sleep(.1)
    return os.getpid()


def background_thread():
    with parallel_backend('loky', in_background_thread=True):
        res = Parallel(n_jobs=2)(
            delayed(sleep_and_return_pid)() for _ in range(4))
    print("parallel call:", res)
    res = Parallel(n_jobs=2)(
        delayed(sleep_and_return_pid)() for _ in range(4))
    print("sequential call:", res)

t = threading.Thread(target=background_thread)
t.start()
t.join()
```

This PR is WIP as some documentation is missing and it should be tested further to make sure it does not lead to un excepted behavior.

### CODE REVIEW

**Comment by kitchoi** [comment]
Thank you @tomMoral (again). Is there anything I can help to get this through? Unfortunately I am no maintainer to help review/approve this pull request.

**Comment by tomMoral** [comment]
You can try the PR to tell us if it solves your use case and if you think the API is flexible enough.
You can also review the code, to see if there is any issue/typo that need to be fixed. It will accelerate the approval process.

**Comment by ogrisel** [comment]
I believe this can be closed in favor of #934 which was recently merged in master. Please reopen if it's not the case.

**Comment by tomMoral** [comment]
Yes! thanks for the clean up!

**Pull request closed without merging**
