### PR TITLE
[MRG] Only run doctests for numpy >= 1.14

### PR DESCRIPTION
**Pull request by lesteve**
master is broken at the moment (see this [AppVeyor build](https://ci.appveyor.com/project/joblib-ci/joblib/build/1.0.1524/job/r9t5roqtknxm60ua#L628) for example) because numpy 1.14 changed numpy array str/repr. This is a fairly minimal change to get it back to green. 

Note: while doing this I discovered failures in rst doctests in `doc/*.rst`. They probably were not run for a while. I'll try to tackle this in a separate PR in the future.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Overall, this is great. Thanks a lot.

It's a pity though that we are loosing some tracking of code coverage. Any chance that we can make sure that codecov still captures the coverage of the doctests?

**Comment by lesteve** [comment]
To me this looks like a codecov bug/quirk but I need to investigate more ...

The last commit only changes the version of codecov and we get a 16% bump in coverage (from 77% to 93%).

**Comment by lesteve** [comment]
codecov is happy, who would have thought. Something I had to sacrifice is that we are not using `--pyargs` in AppVeyor. If this PR is merged, I will open a PR to test the joblib package outside of the git checkout in Travis, which is probably easier.

More details about the codecov issue in https://github.com/codecov/codecov-python/issues/135.

**Comment by ogrisel** [comment]
LGTM, merging!

**Pull request merged**
