### PR TITLE
[MRG] Fix Parallel hanging with exhausted iterator

### LINKED ISSUE #292: Joblib.Parallel hangs when passed an empty iterable (python 2.7)
Currently the parallel loop will hang for the following code snippets
```
from math import sqrt
from joblib import Parallel, delayed

Parallel(n_jobs=2)(delayed(sqrt)(i) for i in range(0))
```
or even just
```
Parallel(n_jobs=2)([])
```
I'm not too familiar with the internals of the parallel loop, but it seems to be because we are requesting a parallel loop with an empty iterable (it works fine for n_jobs=1, i.e. a flat loop). Up until joblib==0.9.2 this would return an empty list.

### PR DESCRIPTION
**Pull request by lesteve**
Fix #292.

### CODE REVIEW

**Comment by aabadie** [comment]
LGTM.

Unfortunately, this doesn't fix the race on appveyor.

**Comment by lesteve** [comment]
> Unfortunately, this doesn't fix the race on appveyor.

I didn't put too much hope into this one :) !

**Comment by ogrisel** [comment]
Please add a CHANGES entry for that. Then +1 for merge.

**Comment by lesteve** [comment]
> Please add a CHANGES entry for that. Then +1 for merge.

Done, merging !

**Comment by lesteve** [comment]
For the record one of the AppVeyor build hung hence the red status of this PR but everything is fine.

**Pull request merged**
