### PR TITLE
Use absolute imports in tests

### PR DESCRIPTION
**Pull request by lesteve**
as advised in the scikit-learn developers guide [here](http://scikit-learn.org/stable/developers/#coding-guidelines). For one this make it a lot easier to check that a test is failing on a released version of joblib but fixed in master.

### CODE REVIEW

**Comment by eickenberg** [comment]
I looked through the changes and found nothing out of the ordinary. Tests are passing.

**Comment by ogrisel** [comment]
Fine with me but this breaks the ability to embed joblib in a third-party project and run the joblib tests in the embedded version. Not a problem for scikit-learn as we strip the tests out anyway.

**Comment by GaelVaroquaux** [comment]
Yes, this is actually a big problem. I am -1 for this.

Do we actually strip the tests out in scikit-learn? Ideally we shouldn't, as it drives the coverage down.

**Comment by lesteve** [comment]
> Fine with me but this breaks the ability to embed joblib in a third-party project and run the joblib tests in the embedded version. Not a problem for scikit-learn as we strip the tests out anyway.

It is easy enough to cd into externals (or wherever your copy of joblib is) and run nosetests there or to set PYTHONPATH when you want to do that. My take on it is that you are going to do that a lot less than trying to run the same tests with two different joblib versions.

**Comment by ogrisel** [comment]
> Do we actually strip the tests out in scikit-learn? Ideally we shouldn't, as it drives the coverage down.

Yes I think the goal was to keep scikit-learn tests as fast as possible, especially on travis. joblib tests are already run by travis on joblib's own travis account.

**Comment by lesteve** [comment]
For completeness sklearn.externals is excluded from the coverage report via the .coveragerc.

**Pull request merged**
