### PR TITLE
[MRG] deadlock between async dispatch and exception handling

### PR DESCRIPTION
**Pull request by ogrisel**
This is a fix for a deadlock identified in #295.

### CODE REVIEW

**Comment by ogrisel** [comment]
Yes it works. @lesteve merge?

**Comment by aabadie** [comment]
LGTM. just curious, are you sure that removing the lock won't introduce other problems ?

**Comment by lesteve** [comment]
> LGTM. just curious, are you sure that removing the lock won't introduce other problems ?

That was the discussion we were having but it looks like @ogrisel is confident the lock wasn't necessary.

Let's merge this one then, thanks !

**Comment by ogrisel** [comment]
> LGTM. just curious, are you sure that removing the lock won't introduce other problems ?

I don't understand why I put it there in the first place: we destroy the pool instance and therefore stop all its thread without waiting for them to complete.

**Pull request merged**
