### PR TITLE
FIX do not use /dev/shm when too small

### PR DESCRIPTION
**Pull request by ogrisel**
This is a fix for #604. This is especially useful to avoid `joblib.Parallel` crash when running in a docker container.

### CODE REVIEW

**Comment by ogrisel** [comment]
@TomAugspurger I would love your feedback here.

**Comment by TomAugspurger** [comment]
FYI, testing this on my next benchmark in ~15 minutes.

**Comment by TomAugspurger** [comment]
+1. Tested the out on a benchmark that previously crashed the container. All went well.

**Comment by ogrisel** [comment]
Thanks for the testing @TomAugspurger!

**Pull request merged**
