### PR TITLE
[MRG] DOC: improve website style and add a logo

### PR DESCRIPTION
**Pull request by aabadie**
This PR slightly improves the new website:
* it adds a new joblib logo to the main pages and also to examples tiles (with some added 'transparency')
* it adds a favicon
* it improves some css: python code background color, title colors, etc
* it removes the search bar since there seemed to be a consensus IRL

### CODE REVIEW

**Comment by aabadie** [comment]
For those interested, the (new) website generated by circle ci is [here](https://60-654608-gh.circle-artifacts.com/0/home/ubuntu/joblib/build/sphinx/html/index.html)

**Comment by aabadie** [comment]
This is ready for review :)

**Comment by GaelVaroquaux** [comment]
Nitpick: transparency on the logo for the favico (look at the tab in firefox: it looks strange).

**Comment by aabadie** [comment]
> transparency on the logo for the favico (look at the tab in firefox: it looks strange).

I guess you are talking of the white background ? I agree, this is not very nice. Are you ok with 100% background transparency ? I fear the black gear won't be very visible.

**Comment by GaelVaroquaux** [comment]
Ok with 100% transparency. If I look at the other logos, this is how they do it. 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by aabadie** [comment]
> Ok with 100% transparency

Done and it's now much nicer indeed

**Comment by aabadie** [comment]
[New version](https://66-654608-gh.circle-artifacts.com/0/home/ubuntu/joblib/build/sphinx/html/index.html)

**Comment by GaelVaroquaux** [comment]
On the phone it looks gorgeous. I'll check on my computer and merge. 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by GaelVaroquaux** [comment]
Looks really great on the computer too. Merging! Thanks

**Comment by aabadie** [comment]
Weird, the examples tiles are still using the default image instead of the joblib one: http://joblib.readthedocs.io/en/latest/auto_examples/index.html

When built locally or on circleci everything is fine. I think there's some caching somewhere with the auto_examples.

**Comment by GaelVaroquaux** [comment]
It's probably that the examples weren't rerun due to the caching of
sphinx-gallery. When we merge modified versions of the examples, it will
be fine.

**Pull request merged**
