### PR TITLE
DOC: Link to docs

### PR DESCRIPTION
**Pull request by larsoner**
I was sad when I couldn't click these to get to the API link, might as well add them!

### CODE REVIEW

**Comment by larsoner** [comment]
Better links visible here: https://joblib--1290.org.readthedocs.build/en/1290/parallel.html

**Review by tomMoral — APPROVED** [review]
LGTM, thanks for improving the doc @larsoner

**Comment by tomMoral** [comment]
The failures are unrelated so merging this one.

**Comment by GaelVaroquaux** [comment]
> thanks for improving the doc @larsoner

+1000

**Pull request merged**
