### PR TITLE
FIX revert back to the fork start method by default

### PR DESCRIPTION
**Pull request by ogrisel**
Fix for #263

### CODE REVIEW

**Comment by ogrisel** [comment]
@GaelVaroquaux CI is all green.

**Comment by lesteve** [comment]
LGTM thanks, merging !

**Comment by lesteve** [comment]
@ogrisel Do we want to do the release ? I can do it if you want and do a PR in scikit-learn as well.

**Comment by ogrisel** [comment]
@lesteve that would be great thanks!

**Comment by GaelVaroquaux** [comment]
Thanks!!!!!

On Fri, Oct 30, 2015 at 07:25:57AM -0700, Olivier Grisel wrote:
> @lesteve that would be great thanks!

> —
> Reply to this email directly or view it on GitHub.*


-- 
    Gael Varoquaux
    Researcher, INRIA Parietal
    NeuroSpin/CEA Saclay , Bat 145, 91191 Gif-sur-Yvette France
    Phone:  ++ 33-1-69-08-79-68
    http://gael-varoquaux.info            http://twitter.com/GaelVaroquaux

**Comment by lesteve** [comment]
I did the 0.9.3 release and create the PR in scikit-learn https://github.com/scikit-learn/scikit-learn/pull/5624.

**Pull request merged**
