### PR TITLE
[MRG] Enable codecov on AppVeyor

### PR DESCRIPTION
**Pull request by lesteve**
Having intermittent problems with errors on AppVeyor that I can not reproduce locally .... :angry:

### CODE REVIEW

**Comment by lesteve** [comment]
On top of that codecov seems to undergo a "minor service outage" at the moment: http://status.codecov.io/

**Comment by aabadie** [comment]
looks like a duplicate of #496 ?

**Comment by lesteve** [comment]
Hmmm I thought I would create the PR, be it only to advertise that I started working on it ... not soon enough apparently, oh well ...

I would rather test the package to avoid setup.py issues like missing data files.

**Comment by lesteve** [comment]
I managed to find a work-around for the problems I was saying. To make a long story short: `ps:` lines should not print to stderr in AppVeyor otherwise this is interpreted as an error.

This seems a feature of Powershell although I don't get this behaviour on my VM ...

**Comment by ogrisel** [comment]
LGTM. @aabadie any comment?

**Comment by lesteve** [comment]
We probably want to wait for codecov to be back to normal before merging.

**Comment by aabadie** [comment]
> @aabadie any comment

yes, the coverage increase (+0.31%) is less than the on hit in #496 (+0.87%). I'm wondering why.

I checked the codecov report on their website. This adds `test/data/create_numpy_pickle.py` to the covered file. I don't understand why.

Maybe it's related to codecov failures today. +1 for waiting for the service to get back to normal.

**Comment by lesteve** [comment]
Looks like the discovery of modules is slightly different with the `--pyargs` argument for some reason. This is why joblib/test/data/create_numpy_pickle.py is found as an additional file and the coverage changes slightly.

Also I believe at the moment that our coverage of multiprocessing is not reliable and this explains thhe change joblib/_parallel_backends.py. I started looking at it a week ago but this doesn't seem like some completely straightforward AFAICT.

All in all I think this should be merged.

**Comment by ogrisel** [comment]
Merged, thank you both @aabadie and @lesteve !

**Pull request merged**
